name: sree-core
version: '${version}'
api-version: '26.2'
main: io.github.sree.SreeCorePlugin

dependencies:
  server:
    Multiverse-Core:
      required: true
      load: BEFORE
    Multiverse-Inventories:
      required: true
      load: BEFORE
    Multiverse-NetherPortals:
      required: true
      load: BEFORE
    Chunky:
      required: true
      load: BEFORE
    voicechat:
      required: false
      load: BEFORE