name: sree-core
version: '${version}'
api-version: '26.2'
main: io.github.sree.SreeCorePlugin

dependencies:
  server:
    Multiverse-Core:
      required: true
      load: AFTER
    Multiverse-Inventories:
      required: true
      load: AFTER
    Chunky:
      required: true
      load: AFTER